# site settings
title: Mayank Vara
subtitle: by HTML5 UP
email: mayankvara@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/mayankvara.github.io" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Ahmedabad
state: GJ
zip_code: 380009
country: India
phone: +91-9033281622

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: mayank.vara
github_url:
gitlab_url: https://gitlab.com/u/mayankvara
googleplus_url: https://plus.google.com/u/0/+mayankvara
instagram_url: https://instagram.com/mayankvara
linkedin_url: https://www.linkedin.com/in/mayankvara
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mayank_vara

# build settings
markdown: kramdown

sass:
  style: compressed
